/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';


export namespace Components {

  interface AppCmp {}
  interface AppCmpAttributes extends StencilHTMLAttributes {}

  interface RootCmp {}
  interface RootCmpAttributes extends StencilHTMLAttributes {}

  interface ProductSearch {}
  interface ProductSearchAttributes extends StencilHTMLAttributes {}

  interface ProductTable {}
  interface ProductTableAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppCmp': Components.AppCmp;
    'RootCmp': Components.RootCmp;
    'ProductSearch': Components.ProductSearch;
    'ProductTable': Components.ProductTable;
  }

  interface StencilIntrinsicElements {
    'app-cmp': Components.AppCmpAttributes;
    'root-cmp': Components.RootCmpAttributes;
    'product-search': Components.ProductSearchAttributes;
    'product-table': Components.ProductTableAttributes;
  }


  interface HTMLAppCmpElement extends Components.AppCmp, HTMLStencilElement {}
  var HTMLAppCmpElement: {
    prototype: HTMLAppCmpElement;
    new (): HTMLAppCmpElement;
  };

  interface HTMLRootCmpElement extends Components.RootCmp, HTMLStencilElement {}
  var HTMLRootCmpElement: {
    prototype: HTMLRootCmpElement;
    new (): HTMLRootCmpElement;
  };

  interface HTMLProductSearchElement extends Components.ProductSearch, HTMLStencilElement {}
  var HTMLProductSearchElement: {
    prototype: HTMLProductSearchElement;
    new (): HTMLProductSearchElement;
  };

  interface HTMLProductTableElement extends Components.ProductTable, HTMLStencilElement {}
  var HTMLProductTableElement: {
    prototype: HTMLProductTableElement;
    new (): HTMLProductTableElement;
  };

  interface HTMLElementTagNameMap {
    'app-cmp': HTMLAppCmpElement
    'root-cmp': HTMLRootCmpElement
    'product-search': HTMLProductSearchElement
    'product-table': HTMLProductTableElement
  }

  interface ElementTagNameMap {
    'app-cmp': HTMLAppCmpElement;
    'root-cmp': HTMLRootCmpElement;
    'product-search': HTMLProductSearchElement;
    'product-table': HTMLProductTableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
